# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json
name: main
description: "My personal hardened Fedora image"
base-image: quay.io/fedora/fedora-bootc
image-version: latest

modules:
  - type: files
    files:
      - source: system/usr
        destination: /usr
      - source: system/etc
        destination: /etc

  - from-file: common/security.yml
  - from-file: desktop/common.yml
  - from-file: desktop/flatpak.yml
  - from-file: services/systemd.yml
