name: main
description: "My personal KDE image"
base-image: quay.io/fedora/fedora-bootc
image-version: latest

modules:
  - from-file: desktop/kde-plasma.yml
  - from-file: packages/packages.yml
  - from-file: packages/flatpak.yml
